### ISSUE TITLE
Installing Elasticsearch and Logstash with Docker

### ISSUE THREAD

**Issue by uojiaku** [fifemon/probes#4]
I am currently running my graphite server with docker and I am able to see my metrics through Grafana. I noticed the slot and jobs metrics are slightly off, which is why I believe installing both elasticsearch and logstash would help. If I were to create/pull docker containers for elasticsearch and logstash would there be any potential complications with Graphite/Grafana?

**Comment by retzkek** [comment]
Hi @uojiaku, there shouldn't be any issues running Elasticsearch and Graphite on the same machine with Docker. Note that it's not really recommended for production, since they'll be competing for drive access, disk cache, etc, but it may not cause any noticeable problems, especially if they're not really busy.

**Comment by uojiaku** [comment]
Ok well I was hoping to use it for production. So if I use the graphite docker image, install the elasticsearch and logstash without docker would I be fine?

**Comment by retzkek** [comment]
The issue isn't docker, it's that graphite and elasticsearch are both high-io applications, so running them on the same machine can be problematic. It really all depends on the load though, so I'd say go ahead and try it.

**Comment by uojiaku** [comment]
Do you think I could just have both Graphite and logstash?

**Comment by retzkek** [comment]
Well, to what end? Logstash is just a tool for moving and manipulating data streams. Yes, it can send data to graphite or elasticsearch, but in different forms. Graphite stores time-series metrics, and does so very efficiently. Elasticsearch is a general document database, and can store just about anything you want to throw at it; Fifemon uses it to store details on every job and slot as well as logs.

**Comment by uojiaku** [comment]
Ok my issue now is that Grafana doesn't display data beyond 6 hours. I would have data from yesterday within 30min-6hours window but after that nothing is stored.
